steps:
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'index.html', 'gs://Demo-Repo/index.html']

artifacts:
  objects:
    location: 'gs://Demo-Repo/'
    paths: ['index.html']
logsBucket: 'gs://Demo-Repo'
